repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.29.1
    hooks:
      - id: check-github-workflows

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: node
        entry: prettier -w --cache
        additional_dependencies:
          - prettier@3.3.3
        types:
          - javascript
        exclude: ^testing/.+
