name: test-and-publish

on:
  push:
    tags:
      - 'v*'
    paths:
      - astro-parallel-build-check/**
      - testing/**
      - .github/workflows/test.yml
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
    branches:
      - main
  pull_request:
    paths:
      - astro-parallel-build-check/**
      - testing/**
      - .github/workflows/test.yml
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
    branches:
      - main

defaults:
  run:
    shell: bash

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        version: [18, 20, 22]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run test
        working-directory: astro-parallel-build-check
        run: pnpm run test

  npm-publish:
    needs: test

    # only run publish on tags
    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Publish to npm
        # --no-git-checks added due to issues with pnpm when publishing from a tag
        # see https://github.com/pnpm/pnpm/issues/5894
        run: |
          pnpm publish --access public --no-git-checks
        working-directory: astro-parallel-build-check
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
